# Makefile extensions for darwin.

# -----------------------------------------------------------------------------
# Variables
# -----------------------------------------------------------------------------

SENZING_DIR ?= /Applications/Senzing.app/Contents/Resources/app/g2
SENZING_TOOLS_SENZING_DIRECTORY ?= $(SENZING_DIR)

DYLD_LIBRARY_PATH := $(SENZING_TOOLS_SENZING_DIRECTORY)/lib:$(SENZING_TOOLS_SENZING_DIRECTORY)/lib/macos

# -----------------------------------------------------------------------------
# Makefile targets supported by all platforms.
# -----------------------------------------------------------------------------

.PHONY: build
build: darwin/amd64

.PHONY: hello-world
hello-world:
	@echo "Hello World, from darwin."

.PHONY: package
package:
	@echo "The 'package' target is not implemented for darwin"

# -----------------------------------------------------------------------------
# Makefile targets supported only by this platform.
# -----------------------------------------------------------------------------

.PHONY: only-darwin
only-darwin:
	@echo "Only darwin has this Makefile target."