# Makefile extensions for linux.

# -----------------------------------------------------------------------------
# Variables
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Makefile targets supported by all platforms.
# -----------------------------------------------------------------------------

.PHONY: build
build: linux/amd64


.PHONY: hello-world
hello-world:
	@echo "Hello World, from linux."


.PHONY: run-serve-grpc
run-serve-grpc: build
	@target/linux-amd64/serve-grpc


.PHONY: run-serve-grpc-trace
run-serve-grpc-trace: build
	@target/linux-amd64/serve-grpc --log-level TRACE --engine-log-level 1

# -----------------------------------------------------------------------------
# Makefile targets supported only by this platform.
# -----------------------------------------------------------------------------

.PHONY: only-linux
only-linux:
	@echo "Only linux has this Makefile target."