name: docker push containers to dockerhub - manual

on:
  workflow_dispatch:

permissions:
  attestations: write
  contents: write
  id-token: write

jobs:
  docker-push-container-to-dockerhub-manual:
    outputs:
      status: ${{ job.status }}
    runs-on: ubuntu-latest

    steps:
      - name: Get repo name
        id: repo-basename
        run: |
          echo "repo=$(basename ${{ github.repository }})" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Build docker image and push to DockerHub
        uses: senzing-factory/github-action-docker-buildx-build@v2
        with:
          image-repository: senzing/${{ steps.repo-basename.outputs.repo }}
          image-tag: latest
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          push: true
          sign-image: true
          username: ${{ secrets.DOCKERHUB_USERNAME }}

  slack-notification:
    needs: [docker-push-container-to-dockerhub-manual]
    if: ${{ always() && contains(fromJSON('["failure", "cancelled"]'), needs.docker-push-container-to-dockerhub-manual.outputs.status) }}
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    uses: senzing-factory/build-resources/.github/workflows/build-failure-slack-notification.yaml@v2
    with:
      job-status: ${{ needs.docker-push-container-to-dockerhub-manual.outputs.status }}
